// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7DFJ30V-3ukkATJbD9cdVRiI9yADrikg',
    appId: '1:725423291545:android:108a90e46d4069aa09cc08',
    messagingSenderId: '725423291545',
    projectId: 'poetry-app-abcb3',
    storageBucket: 'poetry-app-abcb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe9SnSE6KAIrARn2J2LU-_2ZAAKFAtZE8',
    appId: '1:725423291545:ios:7f81b79943763ac109cc08',
    messagingSenderId: '725423291545',
    projectId: 'poetry-app-abcb3',
    storageBucket: 'poetry-app-abcb3.appspot.com',
    iosBundleId: 'com.example.poetsParadise',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFXfXuEN_DB81yJ-raLOj5roe2BEdVYyU',
    appId: '1:725423291545:web:fb040394a28d17d309cc08',
    messagingSenderId: '725423291545',
    projectId: 'poetry-app-abcb3',
    authDomain: 'poetry-app-abcb3.firebaseapp.com',
    storageBucket: 'poetry-app-abcb3.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe9SnSE6KAIrARn2J2LU-_2ZAAKFAtZE8',
    appId: '1:725423291545:ios:7f81b79943763ac109cc08',
    messagingSenderId: '725423291545',
    projectId: 'poetry-app-abcb3',
    storageBucket: 'poetry-app-abcb3.appspot.com',
    iosBundleId: 'com.example.poetsParadise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFXfXuEN_DB81yJ-raLOj5roe2BEdVYyU',
    appId: '1:725423291545:web:defdf6464c93585c09cc08',
    messagingSenderId: '725423291545',
    projectId: 'poetry-app-abcb3',
    authDomain: 'poetry-app-abcb3.firebaseapp.com',
    storageBucket: 'poetry-app-abcb3.appspot.com',
  );

}